export const OPERATOR_SQL = {
  equals: '=',
  not_equals: '!=',
  gt: '>',
  gte: '>=',
  lt: '<',
  lte: '<=',
  contains: 'LIKE',
  starts_with: 'LIKE',
  ends_with: 'LIKE',
  before: '<',
  after: '>',
  isEmpty: 'IS_EMPTY',
  is_not_empty: 'IS_NOT_EMPTY',
};